version: "3.8"

services: 
  database_ignite:
    image: postgres
    container_name: hyperlinkdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hyperlinks
    volumes:
      - pgdata:/data/postgres
  

volumes:
  pgdata:
    driver: local